version: "3.8"

services:
  hcgateway-dashboard:
    build: .
    ports:
      - "8501:8501"
    environment:
      - HCGATEWAY_USERNAME=${HCGATEWAY_USERNAME}
      - HCGATEWAY_PASSWORD=${HCGATEWAY_PASSWORD}
      - LOGGING_LEVEL=${LOGGING_LEVEL:-INFO}
    env_file:
      - .env
