version: "3.8"

services:
  hcgateway-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: hcgateway-dashboard
    ports:
      - "8501:8501"
    environment:
      - HCGATEWAY_USERNAME=${HCGATEWAY_USERNAME}
      - HCGATEWAY_PASSWORD=${HCGATEWAY_PASSWORD}
      - LOGGING_LEVEL=${LOGGING_LEVEL:-INFO}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - hcgateway-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hcgateway.rule=Host(`dashboard.hcgateway.local`)"
      - "traefik.http.services.hcgateway.loadbalancer.server.port=8501"

  # Development service
  hcgateway-dashboard-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: hcgateway-dashboard-dev
    ports:
      - "8502:8501"
    environment:
      - HCGATEWAY_USERNAME=${HCGATEWAY_USERNAME}
      - HCGATEWAY_PASSWORD=${HCGATEWAY_PASSWORD}
      - LOGGING_LEVEL=DEBUG
    env_file:
      - .env
    volumes:
      - .:/app
      - ~/.cache/pip:/home/hcgateway/.cache/pip
    command:
      [
        "streamlit",
        "run",
        "--server.port=8501",
        "--server.address=0.0.0.0",
        "src/hcgateway_dashboard/__main__.py",
        "--server.runOnSave=true",
      ]
    networks:
      - hcgateway-network
    profiles:
      - dev

networks:
  hcgateway-network:
    driver: bridge
