[project]
dependencies    = ["dotenv>=0.9.9", "requests>=2.32.4"]
description     = "Dashboard for HCGateway data"
name            = "hcgateway-dashboard"
readme          = "README.md"
requires-python = ">=3.13"
version         = "0.1.0"

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "ruff>=0.12.7",
]

[tool.ruff.lint]
select = ["ALL"]
